# Generated by Django 4.2.13 on 2024-07-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_form_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.IntegerField(default=8000694996, max_length=10),
        ),
    ]
