# Generated by Django 4.2.13 on 2024-07-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_form_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='phone',
            new_name='phoneno',
        ),
    ]
