# Generated by Django 5.0.6 on 2024-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_form_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='middlename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
